framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        buses:
            messenger.bus.default:
                middleware:
                    - App\Middleware\CustomMiddleware

        transports:
            async_priority_high:
                # https://symfony.com/doc/current/messenger.html#transport-configuration
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                # failed: 'doctrine://default?queue_name=failed'
                # sync: 'sync://'

                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 2000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0

        routing:
            # Route your messages to the transports
             'App\Message\MailQueue': async_priority_high
             'App\Message\MoveToLogMessage': async_priority_high
