twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['admin/custom_horizontal_layout.html.twig']
    paths:
        '%kernel.project_dir%/templates/admin': 'admin'
